name: Automated Builds

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'extras/yamllint-config.yaml'
      - 'scripts/*'
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
      - 'appveyor.yml'
      - 'extras/yamllint-config.yaml'
      - 'scripts/*'

permissions:
  contents: write

jobs:
  linux-appimage:
    name: 🐧 Linux AppImage
    uses: "./.github/workflows/linux-appimage-build.yml"
  linux-cross-appimage:
    name: 🐧 Linux Cross-Compiled AppImage
    uses: "./.github/workflows/linux-cross-appimage-build.yml"
